/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CowsRouteImport } from './routes/cows'
import { Route as HealthRouteImport } from './routes/health'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CowsCowIdRouteImport } from './routes/cows.$cowId'
import { Route as MilkAddRouteImport } from './routes/milk.add'
import { Route as MilkHistoryRouteImport } from './routes/milk.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CowsRoute = CowsRouteImport.update({
  id: '/cows',
  path: '/cows',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CowsCowIdRoute = CowsCowIdRouteImport.update({
  id: '/$cowId',
  path: '/$cowId',
  getParentRoute: () => CowsRoute,
} as any)
const MilkAddRoute = MilkAddRouteImport.update({
  id: '/milk/add',
  path: '/milk/add',
  getParentRoute: () => rootRouteImport,
} as any)
const MilkHistoryRoute = MilkHistoryRouteImport.update({
  id: '/milk/history',
  path: '/milk/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cows': typeof CowsRouteWithChildren
  '/health': typeof HealthRoute
  '/insights': typeof InsightsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/cows/$cowId': typeof CowsCowIdRoute
  '/milk/add': typeof MilkAddRoute
  '/milk/history': typeof MilkHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cows': typeof CowsRouteWithChildren
  '/health': typeof HealthRoute
  '/insights': typeof InsightsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/cows/$cowId': typeof CowsCowIdRoute
  '/milk/add': typeof MilkAddRoute
  '/milk/history': typeof MilkHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cows': typeof CowsRouteWithChildren
  '/health': typeof HealthRoute
  '/insights': typeof InsightsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/cows/$cowId': typeof CowsCowIdRoute
  '/milk/add': typeof MilkAddRoute
  '/milk/history': typeof MilkHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/cows'
    | '/health'
    | '/insights'
    | '/schedule'
    | '/settings'
    | '/cows/$cowId'
    | '/milk/add'
    | '/milk/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/cows'
    | '/health'
    | '/insights'
    | '/schedule'
    | '/settings'
    | '/cows/$cowId'
    | '/milk/add'
    | '/milk/history'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/cows'
    | '/health'
    | '/insights'
    | '/schedule'
    | '/settings'
    | '/cows/$cowId'
    | '/milk/add'
    | '/milk/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CowsRoute: typeof CowsRouteWithChildren
  HealthRoute: typeof HealthRoute
  InsightsRoute: typeof InsightsRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  MilkAddRoute: typeof MilkAddRoute
  MilkHistoryRoute: typeof MilkHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cows': {
      id: '/cows'
      path: '/cows'
      fullPath: '/cows'
      preLoaderRoute: typeof CowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cows/$cowId': {
      id: '/cows/$cowId'
      path: '/$cowId'
      fullPath: '/cows/$cowId'
      preLoaderRoute: typeof CowsCowIdRouteImport
      parentRoute: typeof CowsRoute
    }
    '/milk/add': {
      id: '/milk/add'
      path: '/milk/add'
      fullPath: '/milk/add'
      preLoaderRoute: typeof MilkAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milk/history': {
      id: '/milk/history'
      path: '/milk/history'
      fullPath: '/milk/history'
      preLoaderRoute: typeof MilkHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CowsRouteChildren {
  CowsCowIdRoute: typeof CowsCowIdRoute
}

const CowsRouteChildren: CowsRouteChildren = {
  CowsCowIdRoute: CowsCowIdRoute,
}

const CowsRouteWithChildren = CowsRoute._addFileChildren(CowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CowsRoute: CowsRouteWithChildren,
  HealthRoute: HealthRoute,
  InsightsRoute: InsightsRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  MilkAddRoute: MilkAddRoute,
  MilkHistoryRoute: MilkHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
