/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CowsRouteImport } from './routes/cows'
import { Route as CowsCowIdRouteImport } from './routes/cows.$cowId'
import { Route as MilkAddRouteImport } from './routes/milk.add'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CowsRoute = CowsRouteImport.update({
  id: '/cows',
  path: '/cows',
  getParentRoute: () => rootRouteImport,
} as any)
const CowsCowIdRoute = CowsCowIdRouteImport.update({
  id: '/$cowId',
  path: '/$cowId',
  getParentRoute: () => CowsRoute,
} as any)
const MilkAddRoute = MilkAddRouteImport.update({
  id: '/milk/add',
  path: '/milk/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cows': typeof CowsRouteWithChildren
  '/cows/$cowId': typeof CowsCowIdRoute
  '/milk/add': typeof MilkAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cows': typeof CowsRouteWithChildren
  '/cows/$cowId': typeof CowsCowIdRoute
  '/milk/add': typeof MilkAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cows': typeof CowsRouteWithChildren
  '/cows/$cowId': typeof CowsCowIdRoute
  '/milk/add': typeof MilkAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cows' | '/cows/$cowId' | '/milk/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cows' | '/cows/$cowId' | '/milk/add'
  id: '__root__' | '/' | '/cows' | '/cows/$cowId' | '/milk/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CowsRoute: typeof CowsRouteWithChildren
  MilkAddRoute: typeof MilkAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cows': {
      id: '/cows'
      path: '/cows'
      fullPath: '/cows'
      preLoaderRoute: typeof CowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cows/$cowId': {
      id: '/cows/$cowId'
      path: '/$cowId'
      fullPath: '/cows/$cowId'
      preLoaderRoute: typeof CowsCowIdRouteImport
      parentRoute: typeof CowsRoute
    }
    '/milk/add': {
      id: '/milk/add'
      path: '/milk/add'
      fullPath: '/milk/add'
      preLoaderRoute: typeof MilkAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CowsRouteChildren {
  CowsCowIdRoute: typeof CowsCowIdRoute
}

const CowsRouteChildren: CowsRouteChildren = {
  CowsCowIdRoute: CowsCowIdRoute,
}

const CowsRouteWithChildren = CowsRoute._addFileChildren(CowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CowsRoute: CowsRouteWithChildren,
  MilkAddRoute: MilkAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
