/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CowsRouteImport } from './routes/cows'
import { Route as HealthRouteImport } from './routes/health'
import { Route as CowsCowIdRouteImport } from './routes/cows.$cowId'
import { Route as MilkAddRouteImport } from './routes/milk.add'
import { Route as MilkHistoryRouteImport } from './routes/milk.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CowsRoute = CowsRouteImport.update({
  id: '/cows',
  path: '/cows',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CowsCowIdRoute = CowsCowIdRouteImport.update({
  id: '/$cowId',
  path: '/$cowId',
  getParentRoute: () => CowsRoute,
} as any)
const MilkAddRoute = MilkAddRouteImport.update({
  id: '/milk/add',
  path: '/milk/add',
  getParentRoute: () => rootRouteImport,
} as any)
const MilkHistoryRoute = MilkHistoryRouteImport.update({
  id: '/milk/history',
  path: '/milk/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cows': typeof CowsRouteWithChildren
  '/health': typeof HealthRoute
  '/cows/$cowId': typeof CowsCowIdRoute
  '/milk/add': typeof MilkAddRoute
  '/milk/history': typeof MilkHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cows': typeof CowsRouteWithChildren
  '/health': typeof HealthRoute
  '/cows/$cowId': typeof CowsCowIdRoute
  '/milk/add': typeof MilkAddRoute
  '/milk/history': typeof MilkHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cows': typeof CowsRouteWithChildren
  '/health': typeof HealthRoute
  '/cows/$cowId': typeof CowsCowIdRoute
  '/milk/add': typeof MilkAddRoute
  '/milk/history': typeof MilkHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cows' | '/health' | '/cows/$cowId' | '/milk/add' | '/milk/history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cows' | '/health' | '/cows/$cowId' | '/milk/add' | '/milk/history'
  id:
    | '__root__'
    | '/'
    | '/cows'
    | '/health'
    | '/cows/$cowId'
    | '/milk/add'
    | '/milk/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CowsRoute: typeof CowsRouteWithChildren
  HealthRoute: typeof HealthRoute
  MilkAddRoute: typeof MilkAddRoute
  MilkHistoryRoute: typeof MilkHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cows': {
      id: '/cows'
      path: '/cows'
      fullPath: '/cows'
      preLoaderRoute: typeof CowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cows/$cowId': {
      id: '/cows/$cowId'
      path: '/$cowId'
      fullPath: '/cows/$cowId'
      preLoaderRoute: typeof CowsCowIdRouteImport
      parentRoute: typeof CowsRoute
    }
    '/milk/add': {
      id: '/milk/add'
      path: '/milk/add'
      fullPath: '/milk/add'
      preLoaderRoute: typeof MilkAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milk/history': {
      id: '/milk/history'
      path: '/milk/history'
      fullPath: '/milk/history'
      preLoaderRoute: typeof MilkHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CowsRouteChildren {
  CowsCowIdRoute: typeof CowsCowIdRoute
}

const CowsRouteChildren: CowsRouteChildren = {
  CowsCowIdRoute: CowsCowIdRoute,
}

const CowsRouteWithChildren = CowsRoute._addFileChildren(CowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CowsRoute: CowsRouteWithChildren,
  HealthRoute: HealthRoute,
  MilkAddRoute: MilkAddRoute,
  MilkHistoryRoute: MilkHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
